version: '3'
services:

# system-level services
#--------------------------------


  nginx:
    image: iotcat/ushio-nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/mnt/etc/home.yimian.xyz/nginx/:/etc/nginx/"
      - "/mnt/:/mnt/"
      - "/var/log/nginx/:/var/log/nginx/"
      - "/home/:/home/"
    #network_mode: "host"
    #command: sh /ip.sh & nginx -g daemon off;
    depends_on:
      - php-fpm
      - v2ray
 





# Database
#----------------------------------

# app-level services
# --------------------------------------
  monitor:
    #build: https://github.com/iotcat/ushio-monitor.git
    image: iotcat/ushio-monitor
    container_name: monitor
    restart: always
    command: USER=home.yimian.xyz
    network_mode: "host"

  php-fpm:
    container_name: php-fpm
    image: crunchgeek/php-fpm:7.3
    restart: always
    volumes:
      - "/home/:/home/"
      - "/mnt/:/mnt/"

# common apps
# -------------------------------------




# local apps
# ---------------------------------------
  
  registry:
    image: docker.yimian.xyz/registry
    container_name: registry
    restart: always
    environment:
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/yimian.xyz.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/yimian.xyz.key
    ports:
      - 5000:5000
    volumes:
      - "/mnt/config/ssl/yimian.xyz:/certs"
      - "/var/docker:/var/lib/registry"



  v2ray:
    image: v2ray/official
    container_name: v2ray
    restart: always
    volumes:
      - "/mnt/config/v2ray/config.json.china:/etc/v2ray/config.json"
      - "/var/log/v2ray/:/var/log/v2ray/"




# networks setting
# ------------------------------------
networks:
  default:

